### ISSUE TITLE
Update README with shell usage

### ISSUE THREAD

**Issue by brenix** [WillAbides/kongplete#14]
It is not clear how to properly set up completion within the local shell as part of the README example.

It should be worth mentioning in the README that the output from the `kongplete.InstallCompletions` merely prints out the shell commands a user must run in order to setup completion.

Possibly providing something like the following command for the example shell command in the README: `source <(shell install-completions)`. Thanks :)

**Comment by synfinatic** [comment]
@WillAbides Actually the above print action only seems to be in the unreleased (but tagged) v0.3.0.  I was curious why the change / loss of functionality?
